### ISSUE TITLE
Peer Checklist

### ISSUE THREAD

**Issue by rikkiadtrak** [adtrak/adtrak-slp-boilerplate#1]
# Peer Checklist (New Website)

NB: Issues found should usually be raised as individual issues in Gitlab and assigned to the developer.

# Pre-Live

### Discovery

- [ ] Check Gitlab issues for the history of changes, ensure they are completed where appropriate
- [ ] Check developer checklist on Gitlab - ensure complete, question missing items
- [ ] General browse of the website for issues
- [ ] Check site on mobile device - browse site to find issues
- [ ] Check Lighthouse to seek improvements
- [ ] Does the site have PPC? Does it need pausing?
- [ ] Who is the Internet Marketer for this site? Are they aware the site is nearly ready?

### Design

- [ ] Website has VAT & Registration numbers
- [ ] All phone numbers are clickable
- [ ] Phone numbers display appropriately
- [ ] Pages have relevant images
- [ ] Hero conveys key message(s) for the page
- [ ] Check the contact page has an adequate layout to provide contact details high on the page
- [ ] Hover states and active states of links are user friendly

### Functionality

NB: Much of this will be not applicable

- [ ] Check design & layout of utility pages like cookie policy, terms & conditions, 404
- [ ] Check any complex/non-ordinary functionality performs as expected
- [ ] Check site search works
- [ ] Check social feeds are working

### Ecommerce
- [ ] Register for an account - did everything run smoothly?
- [ ] Complete a test purchase using 'cash on delivery' payment method, or with a £0.00 product - any issues?
- [ ] Thank you page for order is styled appropriately
- [ ] Order Emails are being sent correctly
- [ ] Order Emails are styled appropriately

### Development

- [ ] CSS and JS is minifying
- [ ] Purge is running
- [ ] Check for enqueued scripts - are they all needed? Could they be deferred or even removed?
- [ ] Code review - how could the site code be improved?

## General

- [ ] Does the developer know how the emails and domains are setup, and how they will proceed?
- [ ] Will there be any parked domains?
- [ ] `thanks@` or `Formspree` or `Send In Blue` has been decided for forms
- [ ] If the font is via [Adobe Fonts / Typekit](https://adtrak.lightning.force.com/lightning/r/Password__c/a0J0Y000001TSc5UAG/view), is it being used from the shared account?

## Admin

- [ ] Ensure relevant delivery tasks are completed, and set those that need doing
- [ ] Ensure other disciplines are made aware of the status of the site

# Post-Live

- [ ] Site has been peer checked (copywriting, IM, PM)
- [ ] Full site check
- [ ] Lighthouse check
- [ ] SSL / HTTPS / mixed-content warnings check
- [ ] Confirm redirects are working with developer
- [ ] Check delivery tasks are completed with hours
- [ ] Check service status of hosting and set to active if relevant

**Comment by rikkiadtrak** [comment]
Didn't mean to add to this repo.
